# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake Parker's personal site
email: 
description: > # this means to ignore newlines until "baseurl:"
    Jake Parker is a synthetic biologist interested in the forces which shape \
    molecular evolution, and harnessing that understanding to build new molecules.\
    This site is for thoughts on computational biology, (bio)informatics, synthetic \
    biology, biotech startups, innovation and entrepreneurship. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakeparker.xyz" # the base hostname & protocol for your site
twitter_username: ingeneousmachin
github_username:  genemachines

# Build settings
markdown: kramdown
